on: push
jobs:
  build-node: 
      runs-on: ubuntu-latest
      container: node:20
      steps: 
        - uses: actions/checkout@v4.1.1
        - run: npm install
        - run: npm i -g pm2 && pm2 start index.js && pm2 save && pm2 logs

      
